name: CI - Financial Advisor

on:
  push:
    branches: [ "main", "dev/frontend", "dev/postgres" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and start services
        run: |
          DATABASE_URL=postgresql://financial_user:financial_password@db:5432/financial_db \
          docker compose up -d --build


      - name: Wait for Postgres to be ready
        run: |
          until docker compose exec -T db pg_isready -U financial_user; do
            echo "Waiting for postgres..."
            sleep 2
          done

      - name: Run tests inside API container
        run: |
          docker compose exec -T api pytest -v

      - name: Stop containers
        if: always()
        run: |
          docker compose down -v